-- Meno v1 admin moderation and privacy-conscious product analytics.
-- Apply after supabase/schema.sql.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.answers
  add column if not exists is_hidden boolean not null default false;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text not null check (char_length(session_id) between 8 and 100),
  event_name text not null check (
    event_name in (
      'app_open',
      'question_view',
      'search',
      'category_selected',
      'question_submitted',
      'answer_submitted',
      'helpful_vote'
    )
  ),
  category text,
  entity_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events(created_at desc);
create index if not exists analytics_events_name_created_at_idx
  on public.analytics_events(event_name, created_at desc);
create index if not exists answers_visible_question_idx
  on public.answers(question_id, is_hidden, created_at);

alter table public.admin_users enable row level security;
alter table public.analytics_events enable row level security;

create or replace function public.is_meno_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists (
      select 1 from public.admin_users a where a.user_id = auth.uid()
    );
$$;

revoke all on function public.is_meno_admin() from public, anon;
grant execute on function public.is_meno_admin() to authenticated;

drop policy if exists "Admins read allowlist" on public.admin_users;
create policy "Admins read allowlist"
  on public.admin_users for select
  to authenticated
  using (public.is_meno_admin());

drop policy if exists "Admins read all questions" on public.questions;
create policy "Admins read all questions"
  on public.questions for select
  to authenticated
  using (public.is_meno_admin());

drop policy if exists "Admins moderate questions" on public.questions;
create policy "Admins moderate questions"
  on public.questions for update
  to authenticated
  using (public.is_meno_admin())
  with check (public.is_meno_admin());

drop policy if exists "Anyone reads answers to approved questions" on public.answers;
create policy "Anyone reads visible answers to approved questions"
  on public.answers for select
  to anon, authenticated
  using (
    is_hidden = false
    and exists (
      select 1 from public.questions q
      where q.id = question_id and q.status = 'approved'
    )
  );

drop policy if exists "Admins read all answers" on public.answers;
create policy "Admins read all answers"
  on public.answers for select
  to authenticated
  using (public.is_meno_admin());

drop policy if exists "Admins hide answers" on public.answers;
create policy "Admins hide answers"
  on public.answers for update
  to authenticated
  using (public.is_meno_admin())
  with check (public.is_meno_admin());

drop policy if exists "Clients insert analytics events" on public.analytics_events;
create policy "Clients insert analytics events"
  on public.analytics_events for insert
  to anon, authenticated
  with check (user_id is null or user_id = auth.uid());

drop policy if exists "Admins read analytics events" on public.analytics_events;
create policy "Admins read analytics events"
  on public.analytics_events for select
  to authenticated
  using (public.is_meno_admin());

-- Keep helpful votes unavailable once an answer is moderated out of public view.
create or replace function public.toggle_helpful(answer_id_input uuid)
returns table(is_helpful boolean, helpful_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then raise exception 'Authentication required'; end if;
  if not exists (
    select 1 from public.answers a
    join public.questions q on q.id = a.question_id
    where a.id = answer_id_input and not a.is_hidden and q.status = 'approved'
  ) then raise exception 'Answer is not available'; end if;

  if exists (select 1 from public.helpful_votes where answer_id = answer_id_input and user_id = current_user_id) then
    delete from public.helpful_votes where answer_id = answer_id_input and user_id = current_user_id;
    update public.answers set helpful_count = greatest(public.answers.helpful_count - 1, 0) where id = answer_id_input;
    is_helpful := false;
  else
    insert into public.helpful_votes(answer_id, user_id) values (answer_id_input, current_user_id);
    update public.answers set helpful_count = public.answers.helpful_count + 1 where id = answer_id_input;
    is_helpful := true;
  end if;
  select a.helpful_count into helpful_count from public.answers a where a.id = answer_id_input;
  return next;
end;
$$;

revoke all on function public.toggle_helpful(uuid) from public, anon;
grant execute on function public.toggle_helpful(uuid) to authenticated;

create or replace function public.admin_dashboard_metrics()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  result jsonb;
begin
  if not public.is_meno_admin() then
    raise exception 'Admin access required';
  end if;

  select jsonb_build_object(
    'total_users', (select count(*) from auth.users),
    'anonymous_users', (select count(*) from auth.users where is_anonymous),
    'total_questions', (select count(*) from public.questions),
    'pending_questions', (select count(*) from public.questions where status = 'pending'),
    'approved_questions', (select count(*) from public.questions where status = 'approved'),
    'rejected_questions', (select count(*) from public.questions where status = 'rejected'),
    'total_answers', (select count(*) from public.answers where not is_hidden),
    'total_helpful_votes', (
      select count(*) from public.helpful_votes v
      join public.answers a on a.id = v.answer_id
      where not a.is_hidden
    ),
    'questions_today', (select count(*) from public.questions where created_at >= date_trunc('day', now())),
    'answers_today', (select count(*) from public.answers where created_at >= date_trunc('day', now()) and not is_hidden),
    'new_users_today', (select count(*) from auth.users where created_at >= date_trunc('day', now())),
    'daily_active_users', (
      select count(distinct coalesce(user_id::text, session_id))
      from public.analytics_events
      where created_at >= date_trunc('day', now())
    ),
    'app_opens', (select count(*) from public.analytics_events where event_name = 'app_open'),
    'question_views', (select count(*) from public.analytics_events where event_name = 'question_view'),
    'searches', (select count(*) from public.analytics_events where event_name = 'search'),
    'question_submissions', (select count(*) from public.analytics_events where event_name = 'question_submitted'),
    'answer_submissions', (select count(*) from public.analytics_events where event_name = 'answer_submitted'),
    'helpful_vote_events', (select count(*) from public.analytics_events where event_name = 'helpful_vote'),
    'top_categories', coalesce((
      select jsonb_agg(row_to_json(t))
      from (
        select category, count(*)::int as count
        from public.analytics_events
        where event_name in ('category_selected', 'question_view')
          and category is not null
        group by category order by count(*) desc limit 8
      ) t
    ), '[]'::jsonb),
    'active_days', coalesce((
      select jsonb_agg(row_to_json(d))
      from (
        select created_at::date as day,
          count(distinct coalesce(user_id::text, session_id))::int as count,
          count(*)::int as events
        from public.analytics_events
        where created_at >= current_date - interval '13 days'
        group by created_at::date order by day
      ) d
    ), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.admin_recent_activity()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_meno_admin() then
    raise exception 'Admin access required';
  end if;
  select jsonb_build_object(
    'questions', coalesce((
      select jsonb_agg(row_to_json(q)) from (
        select id, title, status, category, created_at
        from public.questions order by created_at desc limit 8
      ) q
    ), '[]'::jsonb),
    'answers', coalesce((
      select jsonb_agg(row_to_json(a)) from (
        select a.id, a.question_id, left(a.body, 140) as body,
          a.is_hidden, a.created_at
        from public.answers a order by a.created_at desc limit 8
      ) a
    ), '[]'::jsonb),
    'events', coalesce((
      select jsonb_agg(row_to_json(e)) from (
        select event_name, category, created_at
        from public.analytics_events order by created_at desc limit 12
      ) e
    ), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

revoke all on function public.admin_dashboard_metrics() from public, anon;
revoke all on function public.admin_recent_activity() from public, anon;
grant execute on function public.admin_dashboard_metrics() to authenticated;
grant execute on function public.admin_recent_activity() to authenticated;

grant select, update on public.questions to authenticated;
grant select, update on public.answers to authenticated;
grant select on public.admin_users to authenticated;
grant insert on public.analytics_events to anon, authenticated;
grant select on public.analytics_events to authenticated;
