-- Meno v1.1: server-enforced content safety, answer reports and Home banners.
-- Additive/non-destructive: no production table or user content is dropped.

create or replace function public.normalize_moderation_text(input_text text)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  value text := lower(coalesce(input_text, ''));
begin
  value := regexp_replace(value, '[ً-ٰٟۖ-ۭـ]', '', 'g');
  value := translate(value, 'أإآٱ', 'اااا');
  value := regexp_replace(value, '([ء-ي])\1{2,}', '\1', 'g');
  value := regexp_replace(value, '[^a-z0-9ء-ي]+', ' ', 'g');
  return trim(regexp_replace(value, '\s+', ' ', 'g'));
end;
$$;

create table if not exists public.blocked_words (
  id uuid primary key default gen_random_uuid(),
  word text not null check (char_length(trim(word)) between 2 and 100),
  normalized_word text generated always as (
    public.normalize_moderation_text(word)
  ) stored,
  category text not null default 'other'
    check (category in ('abuse', 'racism', 'spam', 'other')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists blocked_words_normalized_word_idx
  on public.blocked_words(normalized_word);
create index if not exists blocked_words_enabled_idx
  on public.blocked_words(enabled) where enabled;

create table if not exists public.answer_reports (
  id uuid primary key default gen_random_uuid(),
  answer_id uuid not null references public.answers(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (
    reason in ('abuse', 'misleading', 'spam', 'inappropriate', 'other')
  ),
  status text not null default 'open'
    check (status in ('open', 'dismissed', 'actioned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(answer_id, reporter_id)
);

create index if not exists answer_reports_status_created_idx
  on public.answer_reports(status, created_at desc);
create index if not exists answer_reports_answer_idx
  on public.answer_reports(answer_id);

create table if not exists public.home_banners (
  id uuid primary key default gen_random_uuid(),
  image_url text not null check (image_url ~ '^https://'),
  title text not null check (char_length(trim(title)) between 2 and 100),
  short_text text not null default '' check (char_length(short_text) <= 240),
  target_url text check (target_url is null or target_url ~ '^https://'),
  type text not null default 'announcement'
    check (type in ('announcement', 'promotion', 'ad')),
  enabled boolean not null default true,
  display_order integer not null default 0 check (display_order >= 0),
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_at is null or start_at is null or end_at > start_at)
);

create index if not exists home_banners_public_order_idx
  on public.home_banners(enabled, display_order, start_at, end_at);

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  object_type text not null
    check (object_type in ('question', 'answer', 'report', 'blocked_word', 'banner')),
  object_id uuid not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists moderation_actions_created_idx
  on public.moderation_actions(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists blocked_words_updated_at on public.blocked_words;
create trigger blocked_words_updated_at before update on public.blocked_words
for each row execute function public.set_updated_at();
drop trigger if exists answer_reports_updated_at on public.answer_reports;
create trigger answer_reports_updated_at before update on public.answer_reports
for each row execute function public.set_updated_at();
drop trigger if exists home_banners_updated_at on public.home_banners;
create trigger home_banners_updated_at before update on public.home_banners
for each row execute function public.set_updated_at();

create or replace function public.contains_blocked_content(input_text text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.blocked_words word
    where word.enabled
      and position(
        ' ' || word.normalized_word || ' '
        in ' ' || public.normalize_moderation_text(input_text) || ' '
      ) > 0
  );
$$;

create or replace function public.is_submission_text_allowed(input_text text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not public.contains_blocked_content(input_text);
$$;

create or replace function public.enforce_allowed_content()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  submitted_text text;
begin
  if tg_table_name = 'questions' then
    submitted_text := concat_ws(' ', new.title, new.body);
  else
    submitted_text := new.body;
  end if;

  if public.contains_blocked_content(submitted_text) then
    raise exception using
      errcode = 'P0001',
      message = 'يرجى تعديل النص، بعض الكلمات المستخدمة غير مسموح بها في Meno.';
  end if;
  return new;
end;
$$;

drop trigger if exists questions_content_safety on public.questions;
create trigger questions_content_safety
before insert or update of title, body on public.questions
for each row execute function public.enforce_allowed_content();

drop trigger if exists answers_content_safety on public.answers;
create trigger answers_content_safety
before insert or update of body on public.answers
for each row execute function public.enforce_allowed_content();

create or replace function public.report_answer(
  answer_id_input uuid,
  reason_input text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if reason_input not in ('abuse', 'misleading', 'spam', 'inappropriate', 'other') then
    raise exception 'Invalid report reason';
  end if;
  if not exists (
    select 1 from public.answers answer
    join public.questions question on question.id = answer.question_id
    where answer.id = answer_id_input
      and not answer.is_hidden
      and question.status = 'approved'
  ) then
    raise exception 'Answer is not available';
  end if;

  insert into public.answer_reports(answer_id, reporter_id, reason)
  values (answer_id_input, auth.uid(), reason_input)
  on conflict (answer_id, reporter_id) do nothing;
  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

create or replace function public.audit_moderation_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  audit_action text;
  audit_type text := tg_table_name;
begin
  if not public.is_meno_admin() then return new; end if;
  if tg_table_name = 'questions' and old.status is distinct from new.status then
    audit_action := 'status:' || new.status::text;
    audit_type := 'question';
  elsif tg_table_name = 'answers' and old.is_hidden is distinct from new.is_hidden then
    audit_action := case when new.is_hidden then 'hide' else 'restore' end;
    audit_type := 'answer';
  elsif tg_table_name = 'answer_reports' and old.status is distinct from new.status then
    audit_action := 'status:' || new.status;
    audit_type := 'report';
  else
    return new;
  end if;
  insert into public.moderation_actions(
    actor_user_id, object_type, object_id, action
  ) values (auth.uid(), audit_type, new.id, audit_action);
  return new;
end;
$$;

drop trigger if exists questions_moderation_audit on public.questions;
create trigger questions_moderation_audit after update on public.questions
for each row execute function public.audit_moderation_change();
drop trigger if exists answers_moderation_audit on public.answers;
create trigger answers_moderation_audit after update on public.answers
for each row execute function public.audit_moderation_change();
drop trigger if exists answer_reports_moderation_audit on public.answer_reports;
create trigger answer_reports_moderation_audit after update on public.answer_reports
for each row execute function public.audit_moderation_change();

alter table public.blocked_words enable row level security;
alter table public.answer_reports enable row level security;
alter table public.home_banners enable row level security;
alter table public.moderation_actions enable row level security;

create policy "Admins manage blocked words" on public.blocked_words
for all to authenticated
using (public.is_meno_admin())
with check (public.is_meno_admin());

create policy "Users submit own answer reports" on public.answer_reports
for insert to authenticated
with check (reporter_id = auth.uid());
create policy "Admins read answer reports" on public.answer_reports
for select to authenticated using (public.is_meno_admin());
create policy "Admins update answer reports" on public.answer_reports
for update to authenticated
using (public.is_meno_admin()) with check (public.is_meno_admin());

create policy "Public reads active banners" on public.home_banners
for select to anon, authenticated
using (
  enabled
  and (start_at is null or start_at <= now())
  and (end_at is null or end_at > now())
);
create policy "Admins read all banners" on public.home_banners
for select to authenticated using (public.is_meno_admin());
create policy "Admins insert banners" on public.home_banners
for insert to authenticated with check (public.is_meno_admin());
create policy "Admins update banners" on public.home_banners
for update to authenticated
using (public.is_meno_admin()) with check (public.is_meno_admin());
create policy "Admins delete banners" on public.home_banners
for delete to authenticated using (public.is_meno_admin());

create policy "Admins read moderation history" on public.moderation_actions
for select to authenticated using (public.is_meno_admin());

revoke all on function public.contains_blocked_content(text) from public, anon, authenticated;
revoke all on function public.enforce_allowed_content() from public, anon, authenticated;
revoke all on function public.report_answer(uuid, text) from public, anon;
revoke all on function public.is_submission_text_allowed(text) from public;
grant execute on function public.is_submission_text_allowed(text) to anon, authenticated;
grant execute on function public.report_answer(uuid, text) to authenticated;

grant select, insert, update, delete on public.blocked_words to authenticated;
grant select, insert, update on public.answer_reports to authenticated;
grant select on public.home_banners to anon, authenticated;
grant insert, update, delete on public.home_banners to authenticated;
grant select on public.moderation_actions to authenticated;
